default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "123456") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "full_body_db") %>

test:
  <<: *default
  database: full_body_test

production:
  <<: *default
  database: full_body_prod
